version: "3"


services:

  _base: &base
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SERVER_ORIGIN=http://localhost:8065
      - PIP_TOOLS_CACHE_DIR=/app/.piptools_cache
    volumes:
      - .:/app

  # base with dependencies
  _python: &python
    <<: *base
    depends_on: ["db"]

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    <<: *python
    command: uvicorn app:app --host 0.0.0.0 --port 8065 --reload
    ports:
      - "8065:8065"
