"""Init tables

Revision ID: 8512fa6a4a52
Revises: 
Create Date: 2022-01-22 17:42:33.225268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8512fa6a4a52"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "katottg",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "region",
                "special",
                "district",
                "community",
                "city",
                "urban_village",
                "village",
                "small_village",
                "municipal_district",
                name="katottgcategory",
            ),
            nullable=False,
        ),
        sa.Column("children_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["katottg.code"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_katottg_category"), "katottg", ["category"], unique=False)
    op.create_index(op.f("ix_katottg_code"), "katottg", ["code"], unique=False)
    op.create_index(op.f("ix_katottg_level"), "katottg", ["level"], unique=False)
    op.create_index(op.f("ix_katottg_name"), "katottg", ["name"], unique=False)
    op.create_index(
        op.f("ix_katottg_parent_id"), "katottg", ["parent_id"], unique=False
    )
    op.create_table(
        "koatuu",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "village",
                "small_village",
                "urban_village",
                "city",
                "municipal_district",
                name="koatuucategory",
            ),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("katottg_code", sa.String(), nullable=True),
        sa.Column("katottg_name", sa.String(), nullable=True),
        sa.Column(
            "katottg_category",
            sa.Enum(
                "region",
                "special",
                "district",
                "community",
                "city",
                "urban_village",
                "village",
                "small_village",
                "municipal_district",
                name="katottgcategory",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_koatuu_category"), "koatuu", ["category"], unique=False)
    op.create_index(op.f("ix_koatuu_code"), "koatuu", ["code"], unique=False)
    op.create_index(
        op.f("ix_koatuu_katottg_category"), "koatuu", ["katottg_category"], unique=False
    )
    op.create_index(
        op.f("ix_koatuu_katottg_code"), "koatuu", ["katottg_code"], unique=False
    )
    op.create_index(
        op.f("ix_koatuu_katottg_name"), "koatuu", ["katottg_name"], unique=False
    )
    op.create_index(op.f("ix_koatuu_name"), "koatuu", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_koatuu_name"), table_name="koatuu")
    op.drop_index(op.f("ix_koatuu_katottg_name"), table_name="koatuu")
    op.drop_index(op.f("ix_koatuu_katottg_code"), table_name="koatuu")
    op.drop_index(op.f("ix_koatuu_katottg_category"), table_name="koatuu")
    op.drop_index(op.f("ix_koatuu_code"), table_name="koatuu")
    op.drop_index(op.f("ix_koatuu_category"), table_name="koatuu")
    op.drop_table("koatuu")
    op.drop_index(op.f("ix_katottg_parent_id"), table_name="katottg")
    op.drop_index(op.f("ix_katottg_name"), table_name="katottg")
    op.drop_index(op.f("ix_katottg_level"), table_name="katottg")
    op.drop_index(op.f("ix_katottg_code"), table_name="katottg")
    op.drop_index(op.f("ix_katottg_category"), table_name="katottg")
    op.drop_table("katottg")
    # ### end Alembic commands ###
